language: c

notifications:
  email: false

before_script:
  # Create tmp directory to keep things clean
  - mkdir -p tmp
  - cd tmp/
  # Install arm-none-eabi-*
  - "curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2012.09-63-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | sudo tar xjf - -C /opt && export PATH=$PATH:/opt/arm-2012.09/bin"
  # Install qemu
  - git clone https://github.com/krasin/qemu_stm32.git
  - cd qemu_stm32/
  - git submodule update --init pixman
  - ./configure --target-list=arm-softmmu
  - make -j7
  - export PATH=$PATH:$(pwd)/arm-softmmu
  - cd ../
  # Install llvm
  - git clone http://llvm.org/git/llvm.git
  - cd llvm && git checkout f5b9110ce1e0d5bc6f96b1e74d110f0cc576324a
  # Install clang
  - cd tools/
  - git clone http://llvm.org/git/clang.git
  - cd clang && git checkout 40ec4d26b7622eb07ad8d5f02da0dd43a1dc74b5
  - cd ../../
  - mkdir -p cbuild
  - cd cbuild
  - cmake ..
  - make -j4
  - export PATH=$PATH:$(pwd)/bin
  - cd ../../..

script:
  - make
  - mkdir -p cbuild
  - cd cbuild
  - cmake ../
  - make
  - make test
  - cd ../
