FROM $BASE_IMAGE:latest

# Install more software
RUN apt-get install -y emacs vim nano tmux

# Copy public key
RUN chown user:user /home/user
RUN mkdir -p /home/user/.ssh
ADD ssh_id /home/user/.ssh/authorized_keys

# Allow passwordless sudo
ADD sudoers /etc/sudoers
RUN chown root:root /etc/sudoers

EXPOSE $PORT0:22
EXPOSE :$PORT1

CMD /bin/bash -c "/usr/sbin/sshd -D"
