#!/usr/bin/env python

import sys
import subprocess


version = { }

header = """/* This file is automatically generated by {0}!
 * Do not edit manually, any manual change will be overwritten.
 */
"""

if len(sys.argv)<3:
    print("Usage:")
    print("  {0} <infile> <outfile>".format(sys.argv[0]))
    sys.exit(1)

#Get the build repos information
version['revision'] = subprocess.check_output(["git", "rev-parse", "HEAD"]).strip()
version['local_revision'] = ""
version['irevision0'] = "0"
version['irevision1'] = "0"
version['tag'] = ""

version['branch'] = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip()

try:
    subprocess.check_output(["git", "diff", "--quiet", "HEAD"])
    version['modified'] = 'false'
except Exception:
    version['modified'] = 'true'

#Apply information to the file template
infile  = open(sys.argv[1], 'r')
outfile = open(sys.argv[2], 'w')

outfile.write(header.format(sys.argv[0], sys.argv[1]))
outfile.write(infile.read().format(**version))

infile.close()
outfile.close()
